"""code snippet language table

Revision ID: 8e80a4cdb778
Revises: 729fb45605c1
Create Date: 2023-03-29 01:29:05.618012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e80a4cdb778'
down_revision = '729fb45605c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_snippet_lang', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_snippet_lang')

    # ### end Alembic commands ###
