"""users table

Revision ID: 2aa065b97550
Revises: d290b6bd9058
Create Date: 2023-04-05 00:27:57.967427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa065b97550'
down_revision = 'd290b6bd9058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitedUsers', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('approvedBy', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('approvedBy')
        batch_op.drop_column('visitedUsers')

    # ### end Alembic commands ###
