"""new table

Revision ID: 593cf3c16802
Revises: 2aa065b97550
Create Date: 2023-04-07 08:32:52.311206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593cf3c16802'
down_revision = '2aa065b97550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_uers', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))
        batch_op.drop_column('visitedUsers')
        batch_op.drop_column('approvedBy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approvedBy', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('visitedUsers', sa.BLOB(), nullable=True))
        batch_op.drop_column('approved_by')
        batch_op.drop_column('visited_uers')

    # ### end Alembic commands ###
