"""users table

Revision ID: 729fb45605c1
Revises: 
Create Date: 2023-03-23 02:43:25.846019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729fb45605c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_snippet', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('code_snippet')

    # ### end Alembic commands ###
