"""new table

Revision ID: c0b58a429014
Revises: 593cf3c16802
Create Date: 2023-04-07 08:37:24.078115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b58a429014'
down_revision = '593cf3c16802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_users', sa.String(), nullable=True))
        batch_op.drop_column('visited_uers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visited_uers', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('visited_users')

    # ### end Alembic commands ###
